FROM nginx:1.27-alpine

RUN apk add --no-cache apache2-utils openssl \
    && mkdir -p /etc/nginx/certs \
    && openssl req -x509 -nodes -newkey rsa:2048 -days 365 \
        -keyout /etc/nginx/certs/podman-web.key \
        -out /etc/nginx/certs/podman-web.crt \
        -subj "/C=ES/ST=Madrid/L=Madrid/O=UNIR/OU=DevOps/CN=podman-web.local" \
    && htpasswd -bc /etc/nginx/.htpasswd alumno unir2026

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/index.html

EXPOSE 443
